# Generated by Django 5.1 on 2024-09-05 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colecao', '0001_initial'),
        ('parametros', '0001_initial'),
        ('tipo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('path', models.ImageField(upload_to='img/%Y/%m/%d/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colecao.collection')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo.type')),
            ],
        ),
        migrations.CreateModel(
            name='CommentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_materials', models.DecimalField(decimal_places=2, max_digits=8)),
                ('labor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('indirect', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.parameters')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.product')),
            ],
        ),
    ]
