# Generated by Django 5.1 on 2024-08-29 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colecao', '0001_initial'),
        ('parametros', '0001_initial'),
        ('produto', '0001_initial'),
        ('tipo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpage',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentproduct',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colecao.collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo.type'),
        ),
        migrations.AddField(
            model_name='commentproduct',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.product'),
        ),
        migrations.AddField(
            model_name='productcost',
            name='parameters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.parameters'),
        ),
    ]
